### ISSUE TITLE
The component crash my app when building in release mode, in react-native 0.64.1.

### ISSUE THREAD

**Issue by AlexandreDao** [GregFrench/react-native-wheel-picker#11]
I think View.propTypes should be replaced by ViewPropTypes or replaced by something like :
```
import {View, ViewPropTypes} from 'react-native';

const viewPropTypes = ViewPropTypes ||  View.propTypes; 
```
to support both older and newer version of RN

**Comment by GregFrench** [comment]
I have gone ahead and removed View.propTypes entirely because I don't think it is actually needed. Try updating to the latest version and see if it fixes your issue. Thanks.

**Comment by AlexandreDao** [comment]
Thanks this fixes the issue
