### ISSUE TITLE
Could not find cn.aigestudio.wheelpicker:WheelPicker:1.0.3

### ISSUE THREAD

**Issue by SandeshVakale** [GregFrench/react-native-wheel-picker#12]
Hello,

I am trying to use wheel Picker in my react native app.
I am using a react-native-wheel-picker library that uses WheelPicker from AigeStudio for android.

But I am getting the following error.

Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find cn.aigestudio.wheelpicker:WheelPicker:1.0.3.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/cn/aigestudio/wheelpicker/WheelPicker/1.0.3/WheelPicker-1.0.3.pom
       - file:/Users/sandeshvakale/.m2/repository/cn/aigestudio/wheelpicker/WheelPicker/1.0.3/WheelPicker-1.0.3.pom
       - file:/Users/sandeshvakale/Desktop/Projects/Maaf/node_modules/react-native/android/cn/aigestudio/wheelpicker/WheelPicker/1.0.3/WheelPicker-1.0.3.pom
       - file:/Users/sandeshvakale/Desktop/Projects/Maaf/node_modules/jsc-android/dist/cn/aigestudio/wheelpicker/WheelPicker/1.0.3/WheelPicker-1.0.3.pom
       - https://dl.google.com/dl/android/maven2/cn/aigestudio/wheelpicker/WheelPicker/1.0.3/WheelPicker-1.0.3.pom
       - https://www.jitpack.io/cn/aigestudio/wheelpicker/WheelPicker/1.0.3/WheelPicker-1.0.3.pom
     Required by:
         project :app > project :gregfrench_react-native-wheel-picker
```

I also forced the library to use the latest 1.1.3 version by making changes in the library Gradle file.

But I get the same error again.

Is anyone facing the same issue?

Thanks in advance for your help.

**Comment by florcalomino** [comment]
Hi, same issue here... It doesnt work on Android. Any ideas?

**Comment by GregFrench** [comment]
The library that this library is built off of for Android: 'cn.aigestudio.wheelpicker:WheelPicker' has seemingly disappeared from all public Maven repositories. I'm not sure what to do or how to resolve this issue at the moment. If anyone could help with this it would be greatly appreciated.

**Comment by flamht** [comment]
facing the same issue here
dont know how to fix yet

>Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not find cn.aigestudio.wheelpicker:WheelPicker:1.0.3.
     Required by:
         project :app

**Comment by JeremyBradshaw7** [comment]
Facing same issue in trying to upgrade to RN 0.66.1, but it's not an issue in my base 0.64.1 version. Not sure why that would be if the android package it depends on has disappeared.

**Comment by 9r4ik** [comment]
I also faced with this when update to 0.66.0 from 0.64.2.
Just do not delete(or add after delete)
```js
jcenter()
```
from buildscript.repositories and allprojects.repositories in android/build.gradle
