### ISSUE TITLE
Is it possible to set the height of individual picker items?

### ISSUE THREAD

**Issue by plowman** [GregFrench/react-native-wheel-picker#14]
Hey there,

First off, thanks for making this! It's by far the closest thing to what we're looking for. Much appreciated!

Right now we're showing two pickers side by side, but I'm not sure how to set the height of each `Picker.Item` to be the same, so they look a little strange side by side:
<img width="348" alt="Screen Shot 2021-11-11 at 11 46 14 AM" src="https://user-images.githubusercontent.com/148066/141359426-7d176953-1518-4dac-a3fd-9d56025aa70b.png">

However, if both of the words have a "y" in them, the height ends up matching, which makes me think the height is defaulting to the contents of each label + value:
<img width="338" alt="Screen Shot 2021-11-11 at 11 49 02 AM" src="https://user-images.githubusercontent.com/148066/141359780-7e4ecfe3-a2ea-463b-a2fa-bb1b38bf8783.png">

Any idea if it's possible to force the height of the picker to be a certain value?

**Comment by GregFrench** [comment]
Hi Ben,

This library no longer works on Android. Please find an alternative solution. I'm deprecating the package on NPM and archiving the repo on GitHub. Sorry for the inconvenience.
