### ISSUE TITLE
Is it possible to set fontFamily for picker items?

### ISSUE THREAD

**Issue by MohammadAzimi** [GregFrench/react-native-wheel-picker#8]
I need to set my custom font family for picker items, but I couldn't achieve it in Android (I didn't test it on iOS)
How should I do this?

I've checked `react-native-picker` it supports font family (being sure by https://github.com/react-native-picker/picker/pull/210)
I'm volunteering to create a PR for it to implement the native side on Android if it's not implemented yet

**Comment by GregFrench** [comment]
Yeah, I don't think this feature exists currently. If you would like to go ahead and implement it and put it in as a PR that would be much appreciated. If it looks good and works as expected I'll merge it and deploy it to both NPM and Yarn. Thanks!

**Comment by MohammadAzimi** [comment]
@GregFrench I wanna create a PR and implement it
 Could you please help me run the lib without any example folder
Any link or something that helps me
My Gmail is available in my profile if issues are not a good place for our chat.

**Comment by GregFrench** [comment]
You could possibly achieve this using NPM Links: https://medium.com/@AidThompsin/how-to-npm-link-to-a-local-version-of-your-dependency-84e82126667a
